### ISSUE TITLE
non-zero exit status

### ISSUE THREAD

**Issue by MuhammadAsadi95** [sara-vanerp/bayesreg#3]
Hi. I still have trouble installing after updating all packages and R & Rstdio. These are my errors
Warning messages:
1: In i.p (...):
   installation of package ‘C: /Users/MOHAMM~1/AppData/Local/Temp/RtmpgfjGpx/file24f0129f2c1a/bayesreg_0.0.0.9000.tar.gz’ had non-zero exit status
2: 1 components of `...` were not used.

We detected these problematic arguments:
* `local`

Did you misspecify an argument?

**Comment by sara-vanerp** [comment]
Did you install the version from the Windows branch or the master branch? Could you try to install the version from the other branch to see if that works?

**Comment by MuhammadAsadi95** [comment]
Thank you for your support.
I have used both branches. But I still have such errors.
Please see some more of these errors below. I hope it becomes clear what I need to fix.


C:/Users/~/R/win-library/4.1/StanHeaders/include/stan/math/rev/core/set_zero_all_adjoints.hpp: At global scope:
C:/Users/~/R/win-library/4.1/StanHeaders/include/stan/math/rev/core/set_zero_all_adjoints.hpp:14:13: warning: 'void stan::math::set_zero_all_adjoints()' defined but not used [-Wunused-function]
 static void set_zero_all_adjoints() {
             ^~~~~~~~~~~~~~~~~~~~~
make: *** [C:/PROGRA~1/R/R-41~1.1/etc/i386/Makeconf:243: stan_files/lm_noNA_normalMixUni_FB.o] Error 1
rm stan_files/lm_noNA_normalMixUni_FB.cc
ERROR: compilation failed for package 'bayesreg'
* removing 'C:/Users/~/R/win-library/4.1/bayesreg'
* restoring previous 'C:/Users/~/R/win-library/4.1/bayesreg'



with regard.

**Comment by sara-vanerp** [comment]
The error message says something about restoring a previous installation. What happens if you try to remove the package first using `remove.packages("bayesreg")`? There is a `bayesreg` package available on CRAN, so it might cause problems if you have installed that as well.

**Comment by MuhammadAsadi95** [comment]
Yes, I deleted it completely.
But I still have the previous installation error.

###

make: *** [C:/PROGRA~1/R/R-41~1.1/etc/x64/Makeconf:243: stan_files/lm_noNA_normalMixUni_FB.o] Error 1
rm stan_files/lm_noNA_normalMixUni_FB.cc
ERROR: compilation failed for package 'bayesreg'
* removing 'C:/Users/Mohammad-PC/Documents/R/win-library/4.1/bayesreg'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/MOHAMM~1/AppData/Local/Temp/Rtmpa2PrHa/file12402e69f3/bayesreg_0.0.0.9000.tar.gz’ had non-zero exit status

###

Is there any ambiguity about "lm_noNA_normalMixUni_FB.cc" error?
Or in case of "had non-zero exit status error", there is no general instruction to fix it?

**Comment by sara-vanerp** [comment]
I am not sure what the problem is here, since the installation works fine on my machine. Could you try installing `Rstan` first to see if that makes a difference? Instructions to do so can be found [here](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started). One problem I can think of is that the Stan models cannot be compiled automatically, for whatever reason, so making sure your machine can compile Stan models, by installing `Rstan` and trying out one of the models might help.

**Comment by MuhammadAsadi95** [comment]
During this time I repeated the installation process many times And I updated Rtools and  reinstalled rstan & StanHeaders from CRAN and github, but still  Bayesreg not installed.
Is it possible to  send .zip or .tar.gz file to my email to try the offline installation?
with regard.

**Comment by sara-vanerp** [comment]
Sure. If you could send me an email (sara.vanerp@gmail.com), or leave your email address here, I can send you the .zip file.

**Comment by MuhammadAsadi95** [comment]
Unbelievable.
Dear Dr. Erp,
1:25 a.m. local time.
Finally, this package was installed.
According to a Persian proverb
There is a lot of hope in despair
as
The end of the dark night is Sunrise.
with regard. 
^_^

**Comment by sara-vanerp** [comment]
Happy to hear that it worked in the end!
